// Code generated by "stringer -type=LineKind"; DO NOT EDIT.

package patch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DiffLine-0]
	_ = x[HeaderLine-1]
	_ = x[HunkLine-2]
	_ = x[ContextLine-3]
	_ = x[AdditionLine-4]
	_ = x[RemovalLine-5]
	_ = x[NoEndOfLineLine-6]
}

const _LineKind_name = "DiffLineHeaderLineHunkLineContextLineAdditionLineRemovalLineNoEndOfLineLine"

var _LineKind_index = [...]uint8{0, 8, 18, 26, 37, 49, 60, 75}

func (i LineKind) String() string {
	if i < 0 || i >= LineKind(len(_LineKind_index)-1) {
		return "LineKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineKind_name[_LineKind_index[i]:_LineKind_index[i+1]]
}
