name: CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go mod download
      - run: |
          cd /home/runner/go/pkg/mod/github.com/libgit2/git2go/v34@v34.0.0
          git submodule update --init
          make install-static