name: CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go mod download
      - name: Install libgit2 statically 
        run: |
          pushd /home/runner/go/pkg/mod/github.com/libgit2/git2go/v34@v34.0.0
          chmod +x ./script/build-libgit2-static.sh
          chmod +x ./script/build-libgit2.sh
          sudo mkdir ./vendor
          pushd ./vendor
          sudo git clone -b v1.5.0 https://github.com/libgit2/libgit2.git
          popd
          sudo make install-static
          popd
          pwd